# alacritty toml
live_config_reload = true

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "Transparent"
opacity = 0.92
blur = true
startup_mode = "Windowed"
title = "blackbeard"
decorations_theme_variant = "Dark"
dynamic_title = false

[font]
size = 9
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

[[colors.indexed_colors]]
color = "0xffbd5e"
index = 16

[[colors.indexed_colors]]
color = "0xff6e5e"
index = 17

[colors.bright]
black = "0x3c4048"
blue = "0x5ea1ff"
cyan = "0x5ef1ff"
green = "0x5eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.normal]
black = "0x16181a"
blue = "0x6ea1ff"
cyan = "0x5ef1ff"
green = "0x6eff6c"
magenta = "0xbd5eff"
red = "0xff6e5e"
white = "0xffffff"
yellow = "0xf1ff5e"

[colors.primary]
background = "0x16181a"
foreground = "0xffffff"

[colors.selection]
background = "0x3c4048"
foreground = "0xffffff"
